### ISSUE TITLE
Unable to Login in.

### ISSUE THREAD

**Issue by IamNickerson** [X1nto/OpenCord#17] opened 2022-04-18 11:17 UTC
Hi I am trying to log in with my alt account nothing seems to happen when I log in it is stuck in login page and when try pressing the log button nothing seems to happen

**Comment by IamNickerson** [comment] 2022-04-18 11:19
Is because of the Discord 2fa thingy which causes nothing to happen?

**Comment by X1nto** [comment] 2022-04-18 11:33
Correct. Closing because it's a duplicate of #15

**Closed by X1nto** 2022-04-18 11:33 UTC

**Comment by IamNickerson** [comment] 2022-04-18 11:46
Ok so i need to remove 2fa? to log in? @X1nto

**Comment by X1nto** [comment] 2022-04-18 11:48
Yes

**Comment by X1nto** [comment] 2022-04-18 11:49
Or use an account without the 2FA

**Comment by IamNickerson** [comment] 2022-04-18 11:51
> Yes

Okay i am also not able to register?

**Comment by IamNickerson** [comment] 2022-04-18 11:52
is it currently work in progress?

**Comment by IamNickerson** [comment] 2022-04-18 11:52
> Or use an account without the 2FA

Alright

**Comment by X1nto** [comment] 2022-04-18 11:55
> is it currently work in progress?

Yes, read the README

**Comment by IamNickerson** [comment] 2022-04-18 11:58
Okay

**Comment by IamNickerson** [comment] 2022-04-18 11:59
it is better to remove the register button as people are totally dumbass and create more issues saying unable to register

**Comment by X1nto** [comment] 2022-04-18 12:02
Why? It'll be added eventually

**Comment by IamNickerson** [comment] 2022-04-18 12:07
Okay
